export const navLinks = [
  {
    id: 1,
    name: 'Home',
    name_de: 'Zuhause',
    name_fr: 'Accueil',
    name_sp: 'Inicio',
    href: '#home',
  },
  {
    id: 2,
    name: 'About',
    name_de: 'Über uns',
    name_fr: 'À propos',
    name_sp: 'Acerca de',
    href: '#about',
  },
  {
    id: 3,
    name: 'Work',
    name_de: 'Arbeiten',
    name_fr: 'Travail',
    name_sp: 'Trabajo',
    href: '#work',
  },
  {
    id: 4,
    name: 'Contact',
    name_de: 'Kontakt',
    name_fr: 'Contact',
    name_sp: 'Contacto',
    href: '#contact',
  },
];


export const clientReviews = [
  {
    id: 1,
    name: 'Shivani Sharma',
    position: 'Director at Veecorp',
    position_de: 'Direktorin bei Veecorp',
    position_fr: 'Directrice chez Veecorp',
    position_sp: 'Directora en Veecorp',
    img: 'assets/review1.png',
    review:
      'Working with Ashutosh was a fantastic experience. He transformed our outdated website into a modern, user-friendly platform. His attention to detail and commitment to quality are unmatched. Highly recommend him for any web dev projects.',
    review_de: 'Die Zusammenarbeit mit Ashutosh war eine fantastische Erfahrung. Er hat unsere veraltete Website in eine moderne, benutzerfreundliche Plattform verwandelt. Seine Liebe zum Detail und sein Engagement für Qualität sind unvergleichlich. Sehr zu empfehlen für Webentwicklungsprojekte.',
    review_fr: "Travailler avec Ashutosh a été une expérience fantastique. Il a transformé notre site Web obsolète en une plateforme moderne et conviviale. Son souci du détail et son engagement envers la qualité sont inégalés. Je le recommande vivement pour tout projet de développement web.",
    review_sp: "Trabajar con Ashutosh fue una experiencia fantástica. Transformó nuestro sitio web anticuado en una plataforma moderna y fácil de usar. Su atención al detalle y su compromiso con la calidad son incomparables. Lo recomiendo encarecidamente para cualquier proyecto de desarrollo web.",
  },
  {
    id: 2,
    name: 'Jay Bhosale',
    position: 'Founder of Bhagwati Consultancy',
    position_de: 'Gründer von Bhagwati Consultancy',
    position_fr: 'Fondateur de Bhagwati Consultancy',
    position_sp: 'Fundador de Bhagwati Consultancy',
    img: 'assets/review2.png',
    review:
      'Ashutosh expertise in web development is truly impressive. He delivered a robust and scalable solution for our e-commerce site, and our online sales have significantly increased since the launch. He’s a true professional! Fantastic work.',
    review_de: 'Ashutoshs Fachkenntnisse in der Webentwicklung sind wirklich beeindruckend. Er lieferte eine robuste und skalierbare Lösung für unsere E-Commerce-Website, und unsere Online-Verkäufe haben seit dem Start erheblich zugenommen. Er ist ein wahrer Profi! Fantastische Arbeit.',
    review_fr: "L'expertise d'Ashutosh en développement web est vraiment impressionnante. Il a fourni une solution robuste et évolutive pour notre site e-commerce, et nos ventes en ligne ont considérablement augmenté depuis le lancement. C'est un vrai professionnel! Un travail fantastique.",
    review_sp: 'La experiencia de Ashutosh en desarrollo web es realmente impresionante. Entregó una solución robusta y escalable para nuestro sitio de comercio electrónico, y nuestras ventas en línea han aumentado significativamente desde el lanzamiento. ¡Es un verdadero profesional! Trabajo fantástico.',
  },
  {
    id: 3,
    name: 'John Dohsas',
    position: 'Project Manager at UrbanTech',
    position_de: 'Projektleiter bei UrbanTech',
    position_fr: 'Chef de projet chez UrbanTech',
    position_sp: 'Gerente de proyecto en UrbanTech',
    img: 'assets/review3.png',
    review:
      'I can’t say enough good things about Ashutosh. He was able to take our complex project requirements and turn them into a seamless, functional software. His problem-solving abilities are outstanding.',
    review_de: 'Ich kann nicht genug Gutes über Ashutosh sagen. Er konnte unsere komplexen Projektanforderungen in eine nahtlose, funktionale Software umsetzen. Seine Problemlösungsfähigkeiten sind herausragend.',
    review_fr: "Je ne peux pas dire assez de bien d'Ashutosh. Il a été capable de transformer nos exigences complexes en un logiciel fluide et fonctionnel. Ses compétences en résolution de problèmes sont remarquables.",
    review_sp: 'No puedo decir suficientes cosas buenas sobre Ashutosh. Pudo tomar nuestros complejos requisitos del proyecto y convertirlos en un software funcional y sin fisuras. Sus habilidades para resolver problemas son sobresalientes.',
  },
  {
    id: 4,
    name: 'Adithan',
    position: 'CEO of BrightStar Enterprises',
    position_de: 'CEO von BrightStar Enterprises',
    position_fr: 'PDG de BrightStar Enterprises',
    position_sp: 'CEO de BrightStar Enterprises',
    img: 'assets/review4.png',
    review:
      'Ashutosh was a pleasure to work with. He understood our requirements perfectly and delivered a website that exceeded our expectations. His skills in both frontend and backend dev are top-notch.',
    review_de: 'Die Zusammenarbeit mit Ashutosh war eine Freude. Er verstand unsere Anforderungen perfekt und lieferte eine Website, die unsere Erwartungen übertraf. Seine Fähigkeiten in der Frontend- und Backend-Entwicklung sind erstklassig.',
    review_fr: "Ce fut un plaisir de travailler avec Ashutosh. Il a parfaitement compris nos besoins et a livré un site web qui a dépassé nos attentes. Ses compétences en développement frontend et backend sont de premier ordre.",
    review_sp: 'Fue un placer trabajar con Ashutosh. Entendió perfectamente nuestros requisitos y entregó un sitio web que superó nuestras expectativas. Sus habilidades en el desarrollo frontend y backend son de primera categoría.',
  },
];


export const myProjects = [
  {
    title: 'Flipkart App - Shopping App | Ecommerce',
    title_de: 'Flipkart App - Shopping App | Ecommerce',
    title_fr: 'Flipkart App - Shopping App | Ecommerce',
    title_sp: 'Flipkart App - Shopping App | Comercio electrónico',
    desc: 'I built a full-featured Flipkart-like shopping app using the MERN stack. The app allows users to browse and purchase products, add new items, and manage accounts with login/registration and secure JWT authentication.',
    desc_de: 'Ich habe eine voll funktionsfähige Flipkart-ähnliche Einkaufs-App mit dem MERN-Stack entwickelt. Die App ermöglicht es Benutzern, Produkte zu durchsuchen und zu kaufen, neue Artikel hinzuzufügen und Konten mit Login/Registrierung und sicherer JWT-Authentifizierung zu verwalten.',
    desc_fr: "J'ai créé une application de shopping complète de type Flipkart en utilisant le stack MERN. L'application permet aux utilisateurs de parcourir et d'acheter des produits, d'ajouter de nouveaux articles et de gérer des comptes avec une connexion/inscription sécurisée par JWT.",
    desc_sp: 'Creé una aplicación de compras completa similar a Flipkart usando el stack MERN. La aplicación permite a los usuarios navegar y comprar productos, agregar nuevos artículos y gestionar cuentas con inicio de sesión/registro y autenticación segura JWT.',
    subdesc: 'Built as a unique Software-as-a-Service. This project highlights my full-stack development skills, combining React.js on the frontend and Node.js for backend APIs.',
    subdesc_de: 'Erstellt als einzigartiges Software-as-a-Service. Dieses Projekt hebt meine Full-Stack-Entwicklungsfähigkeiten hervor, indem React.js im Frontend und Node.js für Backend-APIs kombiniert werden.',
    subdesc_fr: "Développé comme un service SaaS unique. Ce projet met en avant mes compétences en développement full-stack, combinant React.js pour le frontend et Node.js pour les API backend.",
    subdesc_sp: 'Creado como un software único como servicio. Este proyecto resalta mis habilidades de desarrollo full-stack, combinando React.js en el frontend y Node.js para las APIs backend.',
    href: 'https://ashutoshpariharr.github.io/flipkart-app/',
    texture: '/textures/project/project1.mp4',
    logo: '/assets/project-logo1.png',
    logoStyle: {
      backgroundColor: '#2A1816',
      border: '0.2px solid #36201D',
      boxShadow: '0px 0px 60px 0px #AA3C304D',
    },
    spotlight: '/assets/spotlight1.png',
    tags: [
      {
        id: 1,
        name: 'React.js',
        path: '/assets/react.svg',
      },
      {
        id: 2,
        name: 'Node.js',
        path: 'assets/node-js.svg',
      },
      {
        id: 3,
        name: 'Framer Motion',
        path: '/assets/mongodb.svg',
      },
      {
        id: 4,
        name: 'TypeScript',
        path: '/assets/typescript.png',
      },
    ],
  },
  {
    title: 'Meeting Software - Make Quick Meetings',
    title_de: 'Meeting-Software - Schnelle Besprechungen durchführen',
    title_fr: 'Logiciel de Réunion - Organiser des Réunions Rapides',
    title_sp: 'Software de Reuniones - Realiza Reuniones Rápidas',
    desc: 'I developed a feature-rich Zoom-like meeting software designed for seamless virtual communication. The platform supports real-time video conferencing, screen sharing, and chat functionality, providing an intuitive and reliable solution for hosting online meetings.',
    desc_de: 'Ich habe eine funktionsreiche Zoom-ähnliche Meeting-Software entwickelt, die für nahtlose virtuelle Kommunikation ausgelegt ist. Die Plattform unterstützt Echtzeit-Videokonferenzen, Bildschirmfreigabe und Chat-Funktionalität und bietet eine intuitive und zuverlässige Lösung für Online-Meetings.',
    desc_fr: "J'ai développé un logiciel de réunion riche en fonctionnalités, similaire à Zoom, conçu pour une communication virtuelle fluide. La plateforme prend en charge la visioconférence en temps réel, le partage d'écran et la fonctionnalité de chat, offrant une solution intuitive et fiable pour organiser des réunions en ligne.",
    desc_sp: 'Desarrollé un software de reuniones similar a Zoom, con múltiples funciones diseñadas para la comunicación virtual fluida. La plataforma soporta videoconferencias en tiempo real, uso compartido de pantalla y chat, proporcionando una solución intuitiva y confiable para reuniones en línea.',
    subdesc: 'Video Conferencing: High-quality, real-time video and audio, Screen Sharing: Share screens for presentations or collaboration, Chat Functionality: In-meeting messaging for enhanced communication.',
    subdesc_de: 'Videokonferenzen: Hochwertiges Video und Audio in Echtzeit, Bildschirmfreigabe: Freigabe von Bildschirmen für Präsentationen oder Zusammenarbeit, Chat-Funktionalität: Nachrichten während des Meetings zur Verbesserung der Kommunikation.',
    subdesc_fr: 'Visioconférence : Vidéo et audio de haute qualité en temps réel, Partage d\'écran : Partager des écrans pour des présentations ou une collaboration, Fonctionnalité de Chat : Messagerie en réunion pour améliorer la communication.',
    subdesc_sp: 'Videoconferencias: Vídeo y audio en tiempo real de alta calidad, Compartir Pantalla: Compartir pantallas para presentaciones o colaboración, Función de Chat: Mensajería en reuniones para mejorar la comunicación.',
    href: 'https://github.com/ashutoshpariharr/Video-calling-app',
    texture: '/textures/project/project2.mp4',
    logo: '/assets/project-logo2.png',
    logoStyle: {
      backgroundColor: '#13202F',
      border: '0.2px solid #17293E',
      boxShadow: '0px 0px 60px 0px #2F6DB54D',
    },
    spotlight: '/assets/spotlight2.png',
    tags: [
      {
        id: 1,
        name: 'next.js',
        path: '/assets/nextjs.svg',
      },
      {
        id: 2,
        name: 'TailwindCSS',
        path: 'assets/tailwindcss.png',
      },
      {
        id: 3,
        name: 'TypeScript',
        path: '/assets/typescript.png',
      },
      {
        id: 4,
        name: 'Framer Motion',
        path: '/assets/framer.png',
      },
    ],
  },
  {
    title: 'Ping Pong - Play Game Score Send To Email',
    title_de: 'Ping Pong - Spielstand wird per E-Mail gesendet',
    title_fr: 'Ping Pong - Envoyer le Score du Jeu par Email',
    title_sp: 'Ping Pong - Enviar la Puntuación del Juego por Email',
    desc: 'I developed a classic Ping Pong game using Python and Tkinter, offering an engaging, interactive experience. The game features smooth paddle control, a dynamic ball, and score tracking. Each time a new high score is achieved, the game automatically sends a congratulatory email, enhancing the competitive spirit.',
    desc_de: 'Ich habe ein klassisches Ping-Pong-Spiel mit Python und Tkinter entwickelt, das ein fesselndes, interaktives Erlebnis bietet. Das Spiel verfügt über eine reibungslose Schlägersteuerung, einen dynamischen Ball und die Verfolgung des Spielstands. Jedes Mal, wenn ein neuer Höchststand erreicht wird, sendet das Spiel automatisch eine Glückwunsch-E-Mail, um den Wettbewerb zu fördern.',
    desc_fr: "J'ai développé un jeu de Ping Pong classique en utilisant Python et Tkinter, offrant une expérience interactive et engageante. Le jeu propose un contrôle fluide de la raquette, une balle dynamique et un suivi des scores. Chaque fois qu'un nouveau record est atteint, le jeu envoie automatiquement un email de félicitations, renforçant l'esprit de compétition.",
    desc_sp: 'Desarrollé un juego clásico de Ping Pong usando Python y Tkinter, ofreciendo una experiencia interactiva y atractiva. El juego cuenta con un control suave de la pala, una bola dinámica y un seguimiento de la puntuación. Cada vez que se logra una nueva puntuación alta, el juego envía automáticamente un correo electrónico de felicitación, mejorando el espíritu competitivo.',
    subdesc: 'My skills in game development and integrating external functionalities like email notifications, creating a fun and feature-rich experience.',
    subdesc_de: 'Meine Fähigkeiten in der Spieleentwicklung und die Integration externer Funktionen wie E-Mail-Benachrichtigungen schaffen ein unterhaltsames und funktionsreiches Erlebnis.',
    subdesc_fr: "Mes compétences en développement de jeux et l'intégration de fonctionnalités externes comme les notifications par email créent une expérience amusante et riche en fonctionnalités.",
    subdesc_sp: 'Mis habilidades en desarrollo de juegos e integración de funcionalidades externas, como notificaciones por correo electrónico, crean una experiencia divertida y rica en funciones.',
    href: 'https://github.com/ashutoshpariharr/Ping-Pong',
    texture: '/textures/project/project4.mp4',
    logo: '/assets/project-logo4.png',
    logoStyle: {
      backgroundColor: '#0E1F38',
      border: '0.2px solid #1B2642',
      boxShadow: '0px 0px 60px 0px #214F8F4D',
    },
    spotlight: '/assets/spotlight3.png',
    tags: [
      {
        id: 1,
        name: 'Tkinter',
        path: '/assets/notion.svg',
      },
      {
        id: 2,
        name: 'Python',
        path: 'assets/python.svg',
      },
      {
        id: 3,
        name: 'TypeScript',
        path: '/assets/sql.svg',
      },
      {
        id: 4,
        name: 'Framer Motion',
        path: '/assets/selenium.svg',
      },
    ],
  },

  {
    title: 'Portfolio - Showcase All MERN Skills',
    title_de: 'Portfolio - Zeigen Sie alle MERN-Fähigkeiten',
    title_fr: 'Portfolio - Présenter Toutes les Compétences MERN',
    title_sp: 'Portfolio - Mostrar Todas las Habilidades MERN',
    desc: 'I developed a showcase skill portfolio using the MERN stack to highlight my relevant skills. The platform includes user authentication with login and logout functionality, as well as an admin panel for managing content.',
    desc_de: 'Ich habe ein Portfolio mit dem MERN-Stack entwickelt, um meine relevanten Fähigkeiten zu präsentieren. Die Plattform umfasst die Benutzeranmeldung mit Login- und Logout-Funktion sowie ein Admin-Panel zur Verwaltung von Inhalten.',
    desc_fr: "J'ai développé un portfolio de compétences en utilisant le stack MERN pour mettre en valeur mes compétences pertinentes. La plateforme inclut une authentification utilisateur avec connexion et déconnexion, ainsi qu'un panneau d'administration pour la gestion du contenu.",
    desc_sp: 'Desarrollé un portafolio de habilidades usando el stack MERN para resaltar mis habilidades relevantes. La plataforma incluye autenticación de usuarios con funcionalidad de inicio y cierre de sesión, así como un panel de administración para gestionar contenido.',
    subdesc: 'User Authentication: Secure login and logout functionality, Admin Panel: Allows for easy management of portfolio content and user information, Responsive Design',
    subdesc_de: 'Benutzerauthentifizierung: Sichere Login- und Logout-Funktion, Admin-Panel: Ermöglicht eine einfache Verwaltung von Portfolioinhalten und Benutzerdaten, Responsives Design',
    subdesc_fr: 'Authentification Utilisateur : Fonctionnalité sécurisée de connexion et de déconnexion, Panneau d\'administration : Permet une gestion facile du contenu du portfolio et des informations des utilisateurs, Design Responsive',
    subdesc_sp: 'Autenticación de Usuario: Funcionalidad segura de inicio y cierre de sesión, Panel de Administración: Facilita la gestión de contenido del portafolio e información de usuarios, Diseño Responsivo',
    href: 'https://ashutosh-portfolio-mern.web.app/',
    texture: '/textures/project/project3.mp4',
    logo: '/assets/project-logo3.png',
    logoStyle: {
      backgroundColor: '#60f5a1',
      background:
        'linear-gradient(0deg, #60F5A150, #60F5A150), linear-gradient(180deg, rgba(255, 255, 255, 0.9) 0%, rgba(208, 213, 221, 0.8) 100%)',
      border: '0.2px solid rgba(208, 213, 221, 1)',
      boxShadow: '0px 0px 60px 0px rgba(35, 131, 96, 0.3)',
    },
    spotlight: '/assets/spotlight3.png',
    tags: [
      {
        id: 1,
        name: 'React.js',
        path: '/assets/react.svg',
      },
      {
        id: 2,
        name: 'TailwindCSS',
        path: 'assets/tailwindcss.png',
      },
      {
        id: 3,
        name: 'TypeScript',
        path: '/assets/typescript.png',
      },
      {
        id: 4,
        name: 'Framer Motion',
        path: '/assets/framer.png',
      },
    ],
  },
  {
    title: 'UI / UX - Figma Design, Graphic Design',
    title_de: 'UI / UX - Figma-Design, Grafikdesign',
    title_fr: 'UI / UX - Design Figma, Design Graphique',
    title_sp: 'UI / UX - Diseño Figma, Diseño Gráfico',
    desc: 'I recently completed a modern, visually stunning portfolio design using Figma that showcases creativity, functionality, and user-centered design. Every element of the UI was crafted with precision to ensure an engaging user experience, from smooth navigation to responsive layouts. The design seamlessly blends aesthetics with functionality.',
    desc_de: 'Ich habe kürzlich ein modernes, optisch atemberaubendes Portfolio-Design mit Figma abgeschlossen, das Kreativität, Funktionalität und benutzerzentriertes Design präsentiert. Jedes UI-Element wurde präzise entwickelt, um ein fesselndes Benutzererlebnis zu gewährleisten, von der reibungslosen Navigation bis hin zu responsiven Layouts. Das Design vereint nahtlos Ästhetik und Funktionalität.',
    desc_fr: "J'ai récemment terminé un design de portfolio moderne et visuellement époustouflant en utilisant Figma, qui met en valeur la créativité, la fonctionnalité et un design centré sur l'utilisateur. Chaque élément de l'interface utilisateur a été conçu avec précision pour garantir une expérience utilisateur engageante, de la navigation fluide aux mises en page réactives. Le design allie parfaitement esthétique et fonctionnalité.",
    desc_sp: 'Recientemente completé un diseño de portafolio moderno y visualmente impresionante utilizando Figma, que muestra creatividad, funcionalidad y un diseño centrado en el usuario. Cada elemento de la interfaz fue creado con precisión para asegurar una experiencia de usuario atractiva, desde la navegación fluida hasta los diseños receptivos. El diseño combina perfectamente la estética con la funcionalidad.',
    subdesc: 'This portfolio project demonstrates my ability to design elegant and effective UIs that leave a lasting impact.',
    subdesc_de: 'Dieses Portfolio-Projekt demonstriert meine Fähigkeit, elegante und effektive Benutzeroberflächen zu entwerfen, die einen bleibenden Eindruck hinterlassen.',
    subdesc_fr: 'Ce projet de portfolio démontre ma capacité à concevoir des interfaces utilisateur élégantes et efficaces qui laissent une impression durable.',
    subdesc_sp: 'Este proyecto de portafolio demuestra mi capacidad para diseñar interfaces de usuario elegantes y efectivas que dejan un impacto duradero.',
    href: 'https://www.figma.com/design/TMICuVnPBDyRfK9Uy2fS62/Untitled?node-id=0-1&t=7JcxVRobAeZoiDRW-1',
    texture: '/textures/project/project5.mp4',
    logo: '/assets/project-logo5.png',
    logoStyle: {
      backgroundColor: '#1C1A43',
      border: '0.2px solid #252262',
      boxShadow: '0px 0px 60px 0px #635BFF4D',
    },
    spotlight: '/assets/spotlight5.png',
    tags: [
      {
        id: 1,
        name: 'React.js',
        path: '/assets/figma.svg',
      },
      {
        id: 2,
        name: 'TailwindCSS',
        path: 'assets/adobeai.svg',
      },
      {
        id: 3,
        name: 'TypeScript',
        path: '/assets/canva.svg',
      },
      {
        id: 4,
        name: 'Framer Motion',
        path: '/assets/photoshop.svg',
      },
    ],
  },
];

// export const calculateSizes = (isSmall, isMobile, isTablet) => {
//   return {
//     deskScale: isSmall ? 0.05 : isMobile ? 0.06 : 0.065,
//     deskPosition: isMobile ? [0.5, -4.5, 0] : [0.25, -5.5, 0],
//     cubePosition: isSmall ? [4, -5, 0] : isMobile ? [5, -5, 0] : isTablet ? [5, -5, 0] : [9, -5.5, 0],
//     reactLogoPosition: isSmall ? [3, 4, 0] : isMobile ? [5, 4, 0] : isTablet ? [5, 4, 0] : [12, 3, 0],
//     ringPosition: isSmall ? [-5, 7, 0] : isMobile ? [-10, 10, 0] : isTablet ? [-12, 10, 0] : [-24, 10, 0],
//     targetPosition: isSmall ? [-5, -10, -10] : isMobile ? [-9, -10, -10] : isTablet ? [-11, -7, -10] : [-13, -13, -10],
//   };
// };

// Secrate token 

export const botToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJob3N0IjoiaHR0cDovL2FzaHV0b3NoLmljdS8iLCJpZCI6IjY4MzE2YjMzZDBiYThjNGEwODNjODlhOCIsImFjY0lkIjoiNjgzMTY4YjJkZmUyMTRlMDI4MTZiYzUyIiwiaWF0IjoxNzQ4MDY5MTcxfQ.7DMtbSybNq86fFHfaGS7plFIsBDOw1rX4m6cnl7y3gI"; 

export const workExperiences = [
  {
    id: 1,
    name: 'Developer',
    name_de: 'Entwickler',
    name_fr: 'Développeur',
    name_sp: 'Desarrollador',
    pos: 'Full Stack Developer (Data Science)',
    pos_de: 'Full Stack Entwickler (Data Science)',
    pos_fr: 'Développeur Full Stack (Data Science)',
    pos_sp: 'Desarrollador Full Stack (Data Science)',
    duration: '2023 - Present',
    duration_de: '2023 - Gegenwart',
    duration_fr: '2023 - Présent',
    duration_sp: '2023 - Presente',
    title: 'I develop responsive, scalable web applications using the MERN stack, handling both frontend and backend tasks. With expertise in React.js, Node.js, Express.js, and MongoDB, I deliver clean, efficient solutions that meet client needs from start to finish.',
    title_de: 'Ich entwickle responsive, skalierbare Webanwendungen mit dem MERN-Stack und übernehme sowohl Frontend- als auch Backend-Aufgaben. Mit Expertise in React.js, Node.js, Express.js und MongoDB liefere ich saubere, effiziente Lösungen, die den Bedürfnissen der Kunden von Anfang bis Ende entsprechen.',
    title_fr: 'Je développe des applications web réactives et évolutives en utilisant le stack MERN, en gérant à la fois les tâches frontend et backend. Avec une expertise en React.js, Node.js, Express.js et MongoDB, je fournis des solutions propres et efficaces qui répondent aux besoins des clients du début à la fin.',
    title_sp: 'Desarrollo aplicaciones web escalables y receptivas utilizando el stack MERN, manejando tanto tareas de frontend como backend. Con experiencia en React.js, Node.js, Express.js y MongoDB, entrego soluciones limpias y eficientes que cumplen con las necesidades del cliente de principio a fin.',
    icon: '/assets/coding.png',
    animation: 'victory',
  },
  {
    id: 2,
    name: 'Developer',
    name_de: 'Entwickler',
    name_fr: 'Développeur',
    name_sp: 'Desarrollador',
    pos: 'Frontend Developer',
    pos_de: 'Frontend Entwickler',
    pos_fr: 'Développeur Frontend',
    pos_sp: 'Desarrollador Frontend',
    duration: '2022 - 2023',
    duration_de: '2022 - 2023',
    duration_fr: '2022 - 2023',
    duration_sp: '2022 - 2023',
    title: 'I build responsive, user-friendly interfaces using React.js, Next.js, TypeScript and more. I focus on clean design, performance, and seamless user experiences across all devices.',
    title_de: 'Ich entwickle responsive, benutzerfreundliche Benutzeroberflächen mit React.js, Next.js, TypeScript und mehr. Mein Fokus liegt auf sauberem Design, Leistung und nahtlosen Benutzererfahrungen auf allen Geräten.',
    title_fr: 'Je crée des interfaces réactives et conviviales en utilisant React.js, Next.js, TypeScript et plus encore. Je me concentre sur un design épuré, la performance et des expériences utilisateur fluides sur tous les appareils.',
    title_sp: 'Construyo interfaces receptivas y fáciles de usar utilizando React.js, Next.js, TypeScript y más. Me enfoco en el diseño limpio, el rendimiento y las experiencias de usuario fluidas en todos los dispositivos.',
    icon: '/assets/ux-design.png',
    animation: 'clapping',
  },
  {
    id: 3,
    name: 'Junior Developer',
    name_de: 'Junior Entwickler',
    name_fr: 'Développeur Junior',
    name_sp: 'Desarrollador Junior',
    pos: 'Junior UI/UX and Web Developer',
    pos_de: 'Junior UI/UX und Webentwickler',
    pos_fr: 'Développeur Junior UI/UX et Web',
    pos_sp: 'Desarrollador Junior UI/UX y Web',
    duration: '2021 - 2022',
    duration_de: '2021 - 2022',
    duration_fr: '2021 - 2022',
    duration_sp: '2021 - 2022',
    title: 'I create intuitive, user-centered web designs with a focus on both UI/UX and development. Using tools like Figma and Adobe XD, I design responsive layouts and implement them with HTML, CSS, and JavaScript to ensure smooth user experiences and visually appealing interfaces.',
    title_de: 'Ich erstelle intuitive, benutzerzentrierte Webdesigns mit einem Fokus auf UI/UX und Entwicklung. Mit Tools wie Figma und Adobe XD entwerfe ich responsive Layouts und implementiere sie mit HTML, CSS und JavaScript, um reibungslose Benutzererlebnisse und visuell ansprechende Oberflächen zu gewährleisten.',
    title_fr: "Je crée des conceptions web intuitives et centrées sur l'utilisateur en me concentrant à la fois sur l'UI/UX et le développement. En utilisant des outils comme Figma et Adobe XD, je conçois des mises en page réactives et les implémente avec HTML, CSS et JavaScript pour garantir des expériences utilisateur fluides et des interfaces visuellement attrayantes.",
    title_sp: 'Creo diseños web intuitivos centrados en el usuario con un enfoque en UI/UX y desarrollo. Utilizando herramientas como Figma y Adobe XD, diseño layouts responsivos y los implemento con HTML, CSS y JavaScript para asegurar experiencias de usuario fluidas e interfaces visualmente atractivas.',
    icon: '/assets/ui-design.png',
    animation: 'salute',
  },
];

export const iconSlugs = [
  'javascript',
  'react',
  'next-dot-js',
  'tailwindcss',
  'typescript',
  'node-dot-js',
  'redux',
  'python',
  'django',
  'flask',
  'mongodb',
  'html5',
  'css3',
  'figma',
  'postgresql',
  'amazonwebservices',
  'selenium',
  'pandas',
  'github',
  'mui',
  'docker',
];
